### ISSUE TITLE
Add Comments to Code

### ISSUE THREAD

**Issue by shreyaspapi** [shreyaspapi/grid-game#2]
Adding comments will e really helpful to understand the code much better.

**Comment by riddhik84** [comment]
Can I work on this?

**Comment by shreyaspapi** [comment]
Yeah Sure

**Comment by riddhik84** [comment]
Is it already done?

**Comment by richa031** [comment]
is it already done? if not can i work on this?

**Comment by shreyaspapi** [comment]
Yes Its done I am closing the issue
